// Ported from Frontier Station 14 at commit 5be37d18c2 (2024-07-01), MIT licensed.
// Copyright (c) 2017-2024 New Frontiers. Adapted for Serenity.

using Content.Client.UserInterface.Controls;
using Content.Shared._Serenity.Contraband;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Serenity.Contraband;

[GenerateTypedNameReferences]
public sealed partial class ContrabandExchangeMenu : FancyWindow
{
    public event Action? SellRequested;
    public event Action? AppraiseRequested;

    public ContrabandExchangeMenu()
    {
        RobustXamlLoader.Load(this);

        var disclaimer = new FormattedMessage();
        disclaimer.AddText(Loc.GetString("contraband-exchange-disclaimer"));
        Disclaimer.SetMessage(disclaimer);

        SellButton.OnPressed += _ => SellRequested?.Invoke();
        AppraiseButton.OnPressed += _ => AppraiseRequested?.Invoke();
    }

    public void UpdateState(ContrabandExchangeInterfaceState state)
    {
        AppraisalLabel.Text = state.Count == 0
            ? Loc.GetString("contraband-exchange-no-goods")
            : Loc.GetString("contraband-exchange-amount", ("amount", state.Appraisal));
        CountLabel.Text = state.Count.ToString();
        AppraiseButton.Disabled = !state.Enabled;
        SellButton.Disabled = !state.Enabled || state.Count == 0;
    }
}
