#!/usr/bin/env python3
"""
Regenerates Serenity's adult-anatomy marking content from a curated subset of the Afterlight-14
genital sprites (CC-BY-SA, originally S.P.L.U.R.T-tg / Anzuneth / DrSmugleaf).

Only the sprite ART is taken from Afterlight; the prototypes, categories and systems are Serenity's own.
Each output RSI keeps the source RSI's license and copyright string verbatim plus a note that it is a subset.

    python Tools/_Serenity/gen_genital_markings.py <path to Afterlight Resources/Textures/_Afterlight/Genitals>

Outputs (all committed, so this only needs re-running to change the curated set):
    Resources/Textures/_Serenity/Genitals/*.rsi
    Resources/Prototypes/_Serenity/Entities/Mobs/Customization/Markings/genitals.yml
    Resources/Locale/en-US/_Serenity/markings/genitals.ftl
"""
import json
import os
import shutil
import sys

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
TEX_OUT = os.path.join(REPO, "Resources", "Textures", "_Serenity", "Genitals")
YML_OUT = os.path.join(REPO, "Resources", "Prototypes", "_Serenity", "Entities", "Mobs", "Customization", "Markings", "genitals.yml")
FTL_OUT = os.path.join(REPO, "Resources", "Locale", "en-US", "_Serenity", "markings", "genitals.ftl")

# ---- curated set -------------------------------------------------------------------------------------------------
PENIS_SHAPES = [  # (id fragment, display name, state pattern)
    ("Human", "Human", "m_penis_human_{n}_{e}_front"),
    ("Knotted", "Knotted", "m_penis_knotted_{n}_{e}_front_primary"),
    ("Flared", "Flared", "m_penis_flared_{n}_{e}_front_primary"),
    ("Tapered", "Tapered", "m_penis_tapered_{n}_{e}_front_primary"),
    ("Hemi", "Hemipenes", "m_penis_hemi_{n}_{e}_front_primary"),
    ("Nondescript", "Nondescript", "m_penis_nondescript_{n}_{e}_front_primary"),
]
PENIS_SIZES = {2: "Small", 4: "Average", 6: "Large"}
TESTICLE_SIZES = {2: "Small", 4: "Average", 6: "Large"}
BREAST_SIZES = {2: "Small", 5: "Medium", 8: "Large", 12: "Very large", 16: "Huge"}
BUTT_SIZES = {2: "Small", 4: "Average", 6: "Large", 8: "Huge"}
# -----------------------------------------------------------------------------------------------------------------


def load_meta(src, rsi):
    with open(os.path.join(src, rsi, "meta.json"), encoding="utf-8") as f:
        return json.load(f)


def write_rsi(src, rsi, out_name, states):
    meta = load_meta(src, rsi)
    have = {s["name"] for s in meta["states"]}
    missing = [s for s in states if s not in have]
    if missing:
        raise SystemExit(f"{rsi}: source is missing states {missing}")
    out = os.path.join(TEX_OUT, out_name)
    if os.path.isdir(out):
        shutil.rmtree(out)
    os.makedirs(out)
    for s in states:
        shutil.copyfile(os.path.join(src, rsi, s + ".png"), os.path.join(out, s + ".png"))
    new_meta = {
        "version": 1,
        "license": meta["license"],
        "copyright": meta["copyright"] + " (subset of states copied into Serenity from the Afterlight-14 fork)",
        "size": meta["size"],
        "states": [{"name": s, "directions": 4} for s in states],
    }
    with open(os.path.join(out, "meta.json"), "w", encoding="utf-8", newline="\n") as f:
        json.dump(new_meta, f, indent=2)
        f.write("\n")


def marking(mid, category, layer, rsi, state):
    return (
        f"- type: marking\n"
        f"  id: {mid}\n"
        f"  bodyPart: {layer}\n"
        f"  markingCategory: {category}\n"
        f"  followSkinColor: true\n"
        f"  forcedColoring: true\n"
        f"  sprites:\n"
        f"  - sprite: _Serenity/Genitals/{rsi}\n"
        f"    state: {state}\n"
    )


def main():
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    src = sys.argv[1]
    yml = [
        "# GENERATED by Tools/_Serenity/gen_genital_markings.py - edit the script, not this file.\n"
        "# Art: CC-BY-SA, taken from Afterlight-14 (originally S.P.L.U.R.T-tg); see each RSI's meta.json.\n"
        "# All follow the character's skin colour. Every species may use them; sex is not restricted.\n\n"
    ]
    ftl = ["## GENERATED by Tools/_Serenity/gen_genital_markings.py\n\n"
           "markings-category-Breasts = Breasts\n"
           "markings-category-Penis = Penis\n"
           "markings-category-Testicles = Testicles\n"
           "markings-category-Vagina = Vagina\n"
           "markings-category-Butt = Butt\n\n"]

    # penises: flaccid (0) is the marking; erect (1) is copied too, ready for arousal-driven visuals later
    penis_states = []
    for frag, name, pat in PENIS_SHAPES:
        for n, size in PENIS_SIZES.items():
            flaccid, erect = pat.format(n=n, e=0), pat.format(n=n, e=1)
            penis_states += [flaccid, erect]
            mid = f"GenitalPenis{frag}{size}"
            yml.append(marking(mid, "Penis", "Penis", "penises.rsi", flaccid) + "\n")
            ftl.append(f"marking-{mid} = {name}, {size.lower()}\n")
    write_rsi(src, "penises.rsi", "penises.rsi", penis_states)
    ftl.append("\n")

    testicle_states = []
    for n, size in TESTICLE_SIZES.items():
        st = f"m_testicles_pair_{n}_adj"
        testicle_states.append(st)
        mid = f"GenitalTesticles{size}"
        yml.append(marking(mid, "Testicles", "Testicles", "testicles.rsi", st) + "\n")
        ftl.append(f"marking-{mid} = Pair, {size.lower()}\n")
    write_rsi(src, "testicles.rsi", "testicles.rsi", testicle_states)
    ftl.append("\n")

    breast_states = []
    for n, size in BREAST_SIZES.items():
        st = f"m_breasts_pair_{n}_front_primary"
        breast_states.append(st)
        mid = f"GenitalBreasts{size.replace(' ', '')}"
        yml.append(marking(mid, "Breasts", "Breasts", "breasts.rsi", st) + "\n")
        ftl.append(f"marking-{mid} = Pair, {size.lower()}\n")
    write_rsi(src, "breasts.rsi", "breasts.rsi", breast_states)
    ftl.append("\n")

    butt_states = []
    for n, size in BUTT_SIZES.items():
        st = f"m_butt_pair_{n}_adj_primary"
        butt_states.append(st)
        mid = f"GenitalButt{size}"
        yml.append(marking(mid, "Butt", "Butt", "butts.rsi", st) + "\n")
        ftl.append(f"marking-{mid} = {size}\n")
    write_rsi(src, "butts.rsi", "butts.rsi", butt_states)
    ftl.append("\n")

    # vagina: no visible art in the source, so it is a placeholder marking that exists so the anatomy can be
    # chosen in the editor and reported to the intimacy system
    write_rsi(src, "vaginas.rsi", "vaginas.rsi", ["blank"])
    yml.append(marking("GenitalVaginaStandard", "Vagina", "Vagina", "vaginas.rsi", "blank"))
    ftl.append("marking-GenitalVaginaStandard = Standard\n")

    for path, chunks in ((YML_OUT, yml), (FTL_OUT, ftl)):
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write("".join(chunks))
    print("done:", len(penis_states) + len(testicle_states) + len(breast_states) + len(butt_states) + 1, "states")


if __name__ == "__main__":
    main()
