## GENERATED by Tools/_Serenity/gen_genital_markings.py

markings-category-Breasts = Breasts
markings-category-Penis = Penis
markings-category-Testicles = Testicles
markings-category-Vagina = Vagina
markings-category-Butt = Butt

marking-GenitalPenisHumanSmall = Human, small
marking-GenitalPenisHumanAverage = Human, average
marking-GenitalPenisHumanLarge = Human, large
marking-GenitalPenisKnottedSmall = Knotted, small
marking-GenitalPenisKnottedAverage = Knotted, average
marking-GenitalPenisKnottedLarge = Knotted, large
marking-GenitalPenisFlaredSmall = Flared, small
marking-GenitalPenisFlaredAverage = Flared, average
marking-GenitalPenisFlaredLarge = Flared, large
marking-GenitalPenisTaperedSmall = Tapered, small
marking-GenitalPenisTaperedAverage = Tapered, average
marking-GenitalPenisTaperedLarge = Tapered, large
marking-GenitalPenisHemiSmall = Hemipenes, small
marking-GenitalPenisHemiAverage = Hemipenes, average
marking-GenitalPenisHemiLarge = Hemipenes, large
marking-GenitalPenisNondescriptSmall = Nondescript, small
marking-GenitalPenisNondescriptAverage = Nondescript, average
marking-GenitalPenisNondescriptLarge = Nondescript, large

marking-GenitalTesticlesSmall = Pair, small
marking-GenitalTesticlesAverage = Pair, average
marking-GenitalTesticlesLarge = Pair, large

marking-GenitalBreastsSmall = Pair, small
marking-GenitalBreastsMedium = Pair, medium
marking-GenitalBreastsLarge = Pair, large
marking-GenitalBreastsVerylarge = Pair, very large
marking-GenitalBreastsHuge = Pair, huge

marking-GenitalButtSmall = Small
marking-GenitalButtAverage = Average
marking-GenitalButtLarge = Large
marking-GenitalButtHuge = Huge

marking-GenitalVaginaStandard = Standard
