using Content.Client.UserInterface.Controls;
using Content.Shared._Serenity.Medical.Recovery;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Serenity.Medical.Recovery;

[GenerateTypedNameReferences]
public sealed partial class MedicalRecoveryConsoleWindow : FancyWindow
{
    [Dependency] private IGameTiming _timing = default!;

    public event Action? ScanPressed;
    public event Action<NetEntity>? RecoverPressed;

    private static readonly Color CriticalColor = Color.FromHex("#e0a537");
    private static readonly Color DeadColor = Color.FromHex("#d63c3c");
    private static readonly Color LinkedColor = Color.FromHex("#41e0fc");

    /// <summary>
    /// Rows whose bar/countdown are advanced every frame from the client clock, so the
    /// display stays smooth between the server's once-a-second state pushes.
    /// </summary>
    private readonly List<(MedicalRecoveryActiveEntry Entry, ProgressBar? Bar, Label Status)> _activeRows = new();

    public MedicalRecoveryConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ScanButton.OnPressed += _ => ScanPressed?.Invoke();
    }

    public void UpdateState(MedicalRecoveryConsoleState state)
    {
        PadStatusLabel.Text = Loc.GetString(state.PadLinked
            ? "medical-recovery-console-pad-linked"
            : "medical-recovery-console-pad-missing");
        PadStatusLabel.FontColorOverride = state.PadLinked ? LinkedColor : DeadColor;
        RangeLabel.Text = Loc.GetString("medical-recovery-console-range", ("range", (int) state.Range));

        ActiveContainer.RemoveAllChildren();
        _activeRows.Clear();
        foreach (var entry in state.Active)
        {
            ActiveContainer.AddChild(BuildActiveRow(entry));
        }

        NoActiveLabel.Visible = state.Active.Count == 0;

        TargetsContainer.RemoveAllChildren();
        foreach (var target in state.Targets)
        {
            TargetsContainer.AddChild(BuildTargetRow(target, state.PadLinked));
        }

        NoTargetsLabel.Visible = state.Targets.Count == 0;

        UpdateActiveRows();
    }

    private Control BuildActiveRow(MedicalRecoveryActiveEntry entry)
    {
        var box = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(0, 2, 0, 4),
        };

        var header = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };
        header.AddChild(new Label { Text = entry.Name, HorizontalExpand = true, ClipText = true });
        var status = new Label { StyleClasses = { "LabelKeyText" } };
        header.AddChild(status);
        box.AddChild(header);

        ProgressBar? bar = null;
        if (entry.Phase == MedicalRecoveryPhase.Deploying)
        {
            bar = new ProgressBar
            {
                MinValue = 0,
                MaxValue = 1,
                SetHeight = 18,
                HorizontalExpand = true,
            };
            box.AddChild(bar);
        }

        _activeRows.Add((entry, bar, status));
        return box;
    }

    private Control BuildTargetRow(MedicalRecoveryTargetEntry target, bool padLinked)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Thickness(0, 2),
        };

        row.AddChild(new Label
        {
            Text = target.Name,
            HorizontalExpand = true,
            ClipText = true,
        });

        row.AddChild(new Label
        {
            Text = Loc.GetString(target.Dead
                ? "medical-recovery-console-state-dead"
                : "medical-recovery-console-state-critical"),
            FontColorOverride = target.Dead ? DeadColor : CriticalColor,
            MinWidth = 70,
        });

        row.AddChild(new Label
        {
            Text = Loc.GetString("medical-recovery-console-distance", ("distance", (int) MathF.Round(target.Distance))),
            MinWidth = 50,
            Align = Label.AlignMode.Right,
            Margin = new Thickness(0, 0, 8, 0),
        });

        var button = new Button
        {
            Text = Loc.GetString("medical-recovery-console-recover-button"),
            Disabled = !padLinked,
        };
        button.OnPressed += _ => RecoverPressed?.Invoke(target.Entity);
        row.AddChild(button);

        return row;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateActiveRows();
    }

    private void UpdateActiveRows()
    {
        var now = _timing.CurTime;
        foreach (var (entry, bar, status) in _activeRows)
        {
            var remaining = entry.PhaseEnd - now;
            if (remaining < TimeSpan.Zero)
                remaining = TimeSpan.Zero;

            if (entry.Phase == MedicalRecoveryPhase.Deploying)
            {
                var total = (entry.PhaseEnd - entry.PhaseStart).TotalSeconds;
                var elapsed = (now - entry.PhaseStart).TotalSeconds;
                if (bar != null)
                    bar.Value = total <= 0 ? 1f : (float) Math.Clamp(elapsed / total, 0, 1);

                status.Text = Loc.GetString("medical-recovery-console-deploying");
            }
            else
            {
                status.Text = Loc.GetString("medical-recovery-console-arriving",
                    ("seconds", (int) Math.Ceiling(remaining.TotalSeconds)));
            }
        }
    }
}
