using System.Linq;
using Content.Shared._Serenity.Skills;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Serenity.Skills.UI;

/// <summary>
/// Character window tab listing the skills your character knows, grouped by category.
/// Only works for your own character: other players' minds are never sent to this client.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CharacterSkillsControl : Control
{
    [Dependency] private IEntityManager _entMan = default!;
    [Dependency] private IPrototypeManager _proto = default!;

    public CharacterSkillsControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void SetCharacter(EntityUid? character)
    {
        ClearCharacter();
        if (character == null)
            return;

        var known = _entMan.System<SkillSystem>().GetSkills(character.Value)
            .Select(id => _proto.TryIndex(id, out var proto) ? proto : null)
            .OfType<SkillPrototype>()
            .ToList();

        NoneLabel.Visible = known.Count == 0;

        foreach (var group in known.GroupBy(s => s.Category).OrderBy(g => Loc.GetString(g.Key)))
        {
            SkillList.AddChild(new Label
            {
                Text = Loc.GetString(group.Key),
                StyleClasses = { "LabelHeading" },
                Margin = new Thickness(0, 6, 0, 2),
            });

            foreach (var skill in group.OrderBy(s => Loc.GetString(s.Name)))
            {
                SkillList.AddChild(new Label { Text = Loc.GetString(skill.Name) });
                SkillList.AddChild(new RichTextLabel
                {
                    Text = Loc.GetString(skill.Description),
                    StyleClasses = { "LabelSubText" },
                    Margin = new Thickness(8, 0, 0, 4),
                });
            }
        }
    }

    public void ClearCharacter()
    {
        SkillList.RemoveAllChildren();
        NoneLabel.Visible = false;
    }
}
