- type: listing
  id: VendorDoubleStunbaton
  productEntity: DoubleStunbaton
  cost:
    Credit: 556
  categories:
  - SLSecurity
  conditions:
  - !type:ListingLimitedStockCondition
    stock: 2
  - !type:BuyerAccessCondition

- type: listing
  id: VendorPurpleStunbaton
  productEntity: PurpleStunbaton
  cost:
    Credit: 376
  categories:
  - SLSecurity
  conditions:
  - !type:ListingLimitedStockCondition
    stock: 4
  - !type:BuyerAccessCondition

- type: listing
  id: ClothingHandsGlovesCombat
  productEntity: ClothingHandsGlovesCombat
  cost:
    Credit: 399
  categories:
  - SLSecurity
  conditions:
  - !type:ListingLimitedStockCondition
    stock: 4
  - !type:BuyerAccessCondition

- type: listing
  id: ClothingHeadHelmetDredd
  productEntity: ClothingHeadHelmetDredd
  cost:
    Credit: 300
  categories:
  - SLSecurity
  conditions:
  - !type:ListingLimitedStockCondition
    stock: 2
  - !type:BuyerAccessCondition

- type: listing
  id: RedBrutePack
  productEntity: RedBrutePack
  cost:
    Credit: 68
  categories:
  - SLBrigmedic
  conditions:
  - !type:ListingLimitedStockCondition
    stock: 4
  - !type:BuyerAccessCondition
    access: Brigmedic

- type: listing
  id: RedOintment
  productEntity: RedOintment
  cost:
    Credit: 68
  categories:
  - SLBrigmedic
  conditions:
  - !type:ListingLimitedStockCondition
    stock: 4
  - !type:BuyerAccessCondition
    access: Brigmedic

- type: listing
  id: RedPunctPack
  productEntity: RedPunctPack
  cost:
    Credit: 102
  categories:
  - SLBrigmedic
  conditions:
  - !type:ListingLimitedStockCondition
    stock: 4
  - !type:BuyerAccessCondition
    access: Brigmedic

- type: listing
  id: RedLacePack
  productEntity: RedLacePack
  cost:
    Credit: 102
  categories:
  - SLBrigmedic
  conditions:
  - !type:ListingLimitedStockCondition
    stock: 4
  - !type:BuyerAccessCondition
    access: Brigmedic

- type: listing
  id: RedBruizPack
  productEntity: RedBruizPack
  cost:
    Credit: 102
  categories:
  - SLBrigmedic
  conditions:
  - !type:ListingLimitedStockCondition
    stock: 4
  - !type:BuyerAccessCondition
    access: Brigmedic
