using System.Linq;
using System.Numerics;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared._Serenity.Chemistry;
using Content.Shared.Chemistry;
using Content.Shared.Chemistry.Reagent;
using Content.Shared.FixedPoint;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using static Robust.Client.UserInterface.Controls.BoxContainer;

namespace Content.Client._Starlight.Chemistry.UI;

/// <summary>
///     Created by Cookie for multiple servers.
///     Client-side UI used to control a <see cref="SharedChemMaster"/>
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class ModernChemMasterWindow : FancyWindow
{
    [Dependency] private IPrototypeManager _prototypeManager = default!;
    [Dependency] private IEntityManager _entityManager = default!;
    public event Action<BaseButton.ButtonEventArgs, ReagentButton>? OnReagentButtonPressed;
    public event Action<BaseButton.ButtonEventArgs, ReagentId, FixedPoint2, bool>? OnCustomReagentButtonPressed;
    public event Action? OnToggleValveButtonPressed;

    private ChemMasterBoundUserInterfaceState? _lastState;
    private static bool _classicMode; // Static since if you selected it, you probably want this. Dunno why though.

    private ChemMasterReagentAmount _selectedAmount = ChemMasterReagentAmount.U5;
    private FixedPoint2? _customAmount;
    private bool _customSelected;

    private static readonly Dictionary<NetEntity, (string Text, FixedPoint2? Amount, bool Selected)> _customPerChemMaster = new();
    private NetEntity? _chemMasterNetEntity;

    private readonly Vector2 _modernMinSize; // Window size referenced from MinSize attribute
    private static readonly Vector2 ClassicMinSize = new(666, 670); // We specify the Classic MinSize here since the original value is in an upstream file and it needs to be a bit longer for spacing reasons
    private const int MaxReagentNameLength = 32; // Amount of characters before truncating name in modern layout
    private const int MaxClassicReagentNameLength = 24; // Amount of characters before truncating name in classic layout

    // Amount configs for the 2x5 modern grid: 9 numeric amounts + All.
    private static readonly (string Label, ChemMasterReagentAmount Amount)[] AmountConfigs =
    {
        ("1",   ChemMasterReagentAmount.U1),
        ("5",   ChemMasterReagentAmount.U5),
        ("10",  ChemMasterReagentAmount.U10),
        ("15",  ChemMasterReagentAmount.U15),
        ("20",  ChemMasterReagentAmount.U20),
        ("30",  ChemMasterReagentAmount.U30),
        ("40",  ChemMasterReagentAmount.U40),
        ("60",  ChemMasterReagentAmount.U60),
        ("120", ChemMasterReagentAmount.U120),
        (Loc.GetString("chem-master-window-buffer-all-amount"), ChemMasterReagentAmount.All),
    };

    private static bool IsInCustomAmountRange(string s) => int.TryParse(s, out var v) && v > 0 && v <= 1000;
    private bool IsCustomAmountValid(string s) => !string.IsNullOrWhiteSpace(s) && IsInCustomAmountRange(s);

    /// <summary>
    /// Create and initialize the chem master UI client-side. Creates the basic layout,
    /// actual data isn't filled in until the server sends data about the chem master.
    /// </summary>
    public ModernChemMasterWindow()
    {
        RobustXamlLoader.Load(this);
        _modernMinSize = MinSize; // Captures ModernChemMasterWindow.xaml MinSize
        IoCManager.InjectDependencies(this);
        // Plumbing valve.
        ValveButton.OnPressed += _ => OnToggleValveButtonPressed?.Invoke();
        ValveButtonClassic.OnPressed += _ => OnToggleValveButtonPressed?.Invoke();

        SearchBar.OnTextChanged += _ =>
        {
            SearchBarClassic.Text = SearchBar.Text;
            UpdateReagentPrototypes(SearchBar.Text);
        };

        SearchBarClassic.OnTextChanged += _ =>
        {
            SearchBar.Text = SearchBarClassic.Text;
            UpdateReagentPrototypes(SearchBarClassic.Text);
        };

        ClassicTabs.SetTabTitle(0, Loc.GetString("chem-master-window-input-tab"));
        ClassicTabs.SetTabTitle(1, Loc.GetString("chem-master-window-packaging-tab"));

        ModernTabs.SetTabTitle(0, Loc.GetString("chem-master-window-input-tab"));
        ModernTabs.SetTabTitle(1, Loc.GetString("chem-master-window-packaging-tab"));

        // Build the amount 'grid' (2x5)
        BuildAmountGrid(AmountGrid);

        BufferTransferButton.Group = BufferDiscardButton.Group = new ButtonGroup();
        BufferTransferButtonClassic.Group = BufferDiscardButtonClassic.Group = new ButtonGroup();

        // Custom amount - shared validation and per-ChemMaster storage, Modern + Classic textboxes sync
        CustomAmountLineEdit.IsValid = IsInCustomAmountRange;
        CustomAmountLineEditClassic.IsValid = IsInCustomAmountRange;
        CustomAmountLineEdit.OnTextChanged += _ => HandleCustomAmountTextChanged(CustomAmountLineEdit, CustomAmountLineEditClassic, isModern: true);
        CustomAmountLineEditClassic.OnTextChanged += _ => HandleCustomAmountTextChanged(CustomAmountLineEditClassic, CustomAmountLineEdit, isModern: false);
        CustomAmountButton.Disabled = true;
        CustomAmountButton.ToggleMode = true;
        CustomAmountButton.OnPressed += _ =>
        {
            if (!IsCustomAmountValid(CustomAmountLineEdit.Text))
            {
                _customSelected = false;
                CustomAmountButton.Pressed = false;
                SaveCustomPerChemMaster();
                return;
            }
            _customAmount = FixedPoint2.New(int.Parse(CustomAmountLineEdit.Text));
            _customSelected = true;
            CustomAmountButton.Pressed = true;
            DeselectGrid();
            SaveCustomPerChemMaster();
            OnAmountSelected?.Invoke(_selectedAmount);
        };

        ApplyLayout();

        // Layout toggle in title bar, left of close button (same pattern as PopOutFancyWindow).
        if (CloseButton.Parent is { } header)
        {
            var layoutLabel = new Label
            {
                Text = _classicMode
                    ? Loc.GetString("chem-master-window-mode-classic")
                    : Loc.GetString("chem-master-window-mode-modern"),
                VerticalAlignment = VAlignment.Center,
                Margin = new Thickness(0, 0, 8, 0),
            };

            var layoutToggle = new SwitchButton
            {
                VerticalAlignment = VAlignment.Center,
                OffStateText = string.Empty,
                OnStateText = string.Empty,
                Pressed = _classicMode,
                ToolTip = Loc.GetString("chem-master-window-mode-tooltip"),
            };

            layoutToggle.OnPressed += args =>
            {
                _classicMode = layoutToggle.Pressed;
                layoutLabel.Text = _classicMode
                    ? Loc.GetString("chem-master-window-mode-classic")
                    : Loc.GetString("chem-master-window-mode-modern");
                ApplyLayout();
            };

            var layoutContainer = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                VerticalAlignment = VAlignment.Center,
                Margin = new Thickness(0, 0, 6, 0),
                Children = { layoutLabel, layoutToggle },
            };

            header.AddChild(layoutContainer);
            layoutContainer.SetPositionInParent(header.ChildCount - 2);
        }
    }

    /// <summary>
    /// Builds a 2x5 amount selection grid into the given GridContainer.
    /// Both modern tabs get their own grid instance but share the _selectedAmount state.
    /// </summary>
    private void BuildAmountGrid(GridContainer grid)
    {
        var amountGroup = new ButtonGroup();

        for (var idx = 0; idx < AmountConfigs.Length; idx++)
        {
            var (label, amount) = AmountConfigs[idx];
            var btn = new Button
            {
                Access = AccessLevel.Public,
                Text = label,
                ToggleMode = true,
                Group = amountGroup,
                MinSize = new Vector2(46, 0),
                Pressed = !_customSelected && amount == _selectedAmount,
                StyleClasses = { idx == 8 ? StyleClass.ButtonOpenRight : StyleClass.ButtonOpenBoth },
            };

            var capturedAmount = amount;
            btn.OnPressed += _ =>
            {
                _customSelected = false;
                CustomAmountButton.Pressed = false;
                SaveCustomPerChemMaster();
                OnAmountSelected?.Invoke(capturedAmount);
            };

            grid.AddChild(btn);
        }
    }

    private void DeselectGrid() { foreach (var c in AmountGrid.Children) if (c is Button b) b.Pressed = false; }

    private void SyncGrid(GridContainer grid)
    {
        if (_customSelected)
        {
            DeselectGrid();
            return;
        }

        var i = 0;
        foreach (var child in grid.Children)
        {
            if (child is Button btn && i < AmountConfigs.Length)
            {
                btn.Pressed = AmountConfigs[i].Amount == _selectedAmount;
                i++;
            }
        }
    }

    private void SaveCustomPerChemMaster() { if (_chemMasterNetEntity is {} id) _customPerChemMaster[id] = (CustomAmountLineEdit.Text, _customAmount, _customSelected); }

    private void HandleCustomAmountTextChanged(LineEdit source, LineEdit target, bool isModern)
    {
        if (target.Text != source.Text)
            target.Text = source.Text;
        if (isModern)
            CustomAmountButton.Disabled = !IsCustomAmountValid(source.Text);
        if (_customSelected)
        {
            if (IsCustomAmountValid(source.Text) && int.TryParse(source.Text, out var v))
                _customAmount = FixedPoint2.New(v);
            else
            {
                _customAmount = null;
                _customSelected = false;
                if (isModern)
                    CustomAmountButton.Pressed = false;
            }
        }
        SaveCustomPerChemMaster();
        UpdateClassicCustomButtons();
    }

    private void UpdateClassicCustomButtons()
    {
        var valid = IsCustomAmountValid(CustomAmountLineEditClassic.Text);
        void UpdateIn(Control root)
        {
            foreach (var child in root.Children)
            {
                if (child is ReagentButton rb && rb.Text == "#")
                    rb.Disabled = !valid;
                else if (child is Control c)
                    UpdateIn(c);
            }
        }
        UpdateIn(BufferInfoClassic);
        UpdateIn(InputContainerInfoClassic);
    }

    public void SetChemMasterEntity(NetEntity id)
    {
        _chemMasterNetEntity = id;
        if (!_customPerChemMaster.TryGetValue(id, out var s)) return;
        CustomAmountLineEdit.Text = s.Text;
        CustomAmountLineEditClassic.Text = s.Text;
        _customAmount = s.Amount;
        _customSelected = s.Selected;
        CustomAmountButton.Disabled = string.IsNullOrWhiteSpace(s.Text) || (CustomAmountLineEdit!.IsValid != null && !CustomAmountLineEdit!.IsValid(s.Text));
        CustomAmountButton.Pressed = _customSelected && !CustomAmountButton.Disabled;
        _customSelected = CustomAmountButton.Pressed;
        UpdateClassicCustomButtons();
        SyncGrid(AmountGrid);
    }

    /// <summary>
    /// Removes cached custom-amount state for the specified ChemMaster entity.
    /// </summary>
    /// <param name="id">The ChemMaster entity whose custom-amount state should be removed.</param>
    public static void ClearCustomForEntity(NetEntity id) => _customPerChemMaster.Remove(id);

    protected override void Dispose(bool disposing)
    {
        if (disposing && _chemMasterNetEntity is {} id)
            _customPerChemMaster.Remove(id);
        base.Dispose(disposing);
    }

    private void ApplyLayout()
    {
        ModernTabs.Visible = !_classicMode;
        ClassicTabs.Visible = _classicMode;

        var targetSize = _classicMode ? ClassicMinSize : _modernMinSize;
        MinSize = targetSize;
        // Force window to specified dimensions, MinSize alone doesn't shrink an already larger window
        SetSize = targetSize;
        if (!_classicMode)
        {
            CustomAmountButton.Disabled = !IsCustomAmountValid(CustomAmountLineEdit.Text);
        }
        else
        {
            UpdateClassicCustomButtons();
        }
    }

    private ReagentButton MakeReagentButton(string text, ChemMasterReagentAmount amount, ReagentId id, bool isBuffer, string styleClass)
    {
        var reagentTransferButton = new ReagentButton(text, amount, id, isBuffer, styleClass);
        reagentTransferButton.OnPressed += args
            => OnReagentButtonPressed?.Invoke(args, reagentTransferButton);
        return reagentTransferButton;
    }

    /// <summary>
    /// Truncates a reagent name with an ellipsis if it exceeds the max length.
    /// Returns the display name and a tooltip with the full name. No tooltip is shown when untruncated.
    /// </summary>
    private static (string display, string? toolTip) TruncateReagentName(string name, int maxLength)
    {
        if (name.Length <= maxLength)
            return (name, null);

        return (name.Substring(0, maxLength).TrimEnd() + "...", name);
    }

    /// <summary>
    /// Classic mode only: generates the full set of per-row amount buttons.
    /// Modern mode rows are buttons themselves - this is not called for them.
    /// </summary>
    private List<ReagentButton> CreateReagentTransferButtons(ReagentId reagent, bool isBuffer, bool addReagentButtons)
    {
        if (!addReagentButtons)
            return new List<ReagentButton>();

        // Classic: full button strip with # preceding 1 for custom amount
        var buttons = new List<ReagentButton>();

        var hashButton = new ReagentButton("#", ChemMasterReagentAmount.U1, reagent, isBuffer, StyleClass.ButtonOpenRight)
        {
            Disabled = !IsCustomAmountValid(CustomAmountLineEditClassic.Text)
        };
        hashButton.OnPressed += a => { if (IsCustomAmountValid(CustomAmountLineEditClassic.Text) && int.TryParse(CustomAmountLineEditClassic.Text, out var v)) OnCustomReagentButtonPressed?.Invoke(a, reagent, FixedPoint2.New(v), isBuffer); };
        buttons.Add(hashButton);

        var buttonConfigs = new (string text, ChemMasterReagentAmount amount, string styleClass)[]
        {
            ("1",   ChemMasterReagentAmount.U1,   StyleClass.ButtonOpenBoth),
            ("5",   ChemMasterReagentAmount.U5,   StyleClass.ButtonOpenBoth),
            ("10",  ChemMasterReagentAmount.U10,  StyleClass.ButtonOpenBoth),
            ("15",  ChemMasterReagentAmount.U15,  StyleClass.ButtonOpenBoth),
            ("20",  ChemMasterReagentAmount.U20,  StyleClass.ButtonOpenBoth),
            ("30",  ChemMasterReagentAmount.U30,  StyleClass.ButtonOpenBoth),
            ("40",  ChemMasterReagentAmount.U40,  StyleClass.ButtonOpenBoth),
            ("60",  ChemMasterReagentAmount.U60,  StyleClass.ButtonOpenBoth),
            ("120", ChemMasterReagentAmount.U120, StyleClass.ButtonOpenBoth),
            (Loc.GetString("chem-master-window-buffer-all-amount"), ChemMasterReagentAmount.All, StyleClass.ButtonOpenLeft),
        };

        foreach (var (text, amount, styleClass) in buttonConfigs)
        {
            buttons.Add(MakeReagentButton(text, amount, reagent, isBuffer, styleClass));
        }

        return buttons;
    }

    /// <summary>
    /// Update the UI state when new state data is received from the server.
    /// </summary>
    public void UpdateState(BoundUserInterfaceState state)
    {
        var castState = (ChemMasterBoundUserInterfaceState)state;
        _lastState = castState;

        UpdatePanelInfo(castState);

        // Keep both layouts in sync with the server state.
        InputEjectButton.Disabled = castState.InputContainerInfo is null;
        InputEjectButtonClassic.Disabled = castState.InputContainerInfo is null;

        var valveText = Loc.GetString(castState.ValveOpen
            ? "chem-master-window-valve-open"
            : "chem-master-window-valve-closed");

        ValveButton.Text = valveText;
        ValveButtonClassic.Text = valveText;

        UpdatePackaging(castState);
    }

    // Serenity: the packaging tab reads its sections/selection from the networked component and its
    // buffer contents from the UI state.
    private void UpdatePackaging(ChemMasterBoundUserInterfaceState state)
    {
        if (_chemMasterNetEntity is not { } net ||
            !_entityManager.TryGetEntity(net, out var uid) ||
            !_entityManager.TryGetComponent(uid, out ChemMasterPackagingComponent? packaging))
        {
            return;
        }

        var sys = _entityManager.System<ChemMasterPackagingSystem>();
        PackagingPanel.Update(state, packaging, sys);
        PackagingPanelClassic.Update(state, packaging, sys);
    }

    private void UpdatePanelInfo(ChemMasterBoundUserInterfaceState state)
    {
        BufferTransferButton.Pressed = state.Mode == ChemMasterMode.Transfer;
        BufferDiscardButton.Pressed = state.Mode == ChemMasterMode.Discard;
        BufferTransferButtonClassic.Pressed = state.Mode == ChemMasterMode.Transfer;
        BufferDiscardButtonClassic.Pressed = state.Mode == ChemMasterMode.Discard;

        // Modern layout containers
        BuildContainerUI(InputContainerInfo, state.InputContainerInfo, true, modernMode: true);

        // Classic layout containers
        BuildContainerUI(InputContainerInfoClassic, state.InputContainerInfo, true, modernMode: false);

        BufferInfo.Children.Clear();
        BufferInfoClassic.Children.Clear();

        var sortLabel = state.SortingType switch
        {
            ChemMasterSortingType.Alphabetical => Loc.GetString("chem-master-window-sort-type-alphabetical"),
            ChemMasterSortingType.Quantity => Loc.GetString("chem-master-window-sort-type-quantity"),
            ChemMasterSortingType.Latest => Loc.GetString("chem-master-window-sort-type-latest"),
            _ => Loc.GetString("chem-master-window-sort-type-none")
        };
        BufferSortButton.Text = sortLabel;
        BufferSortButtonClassic.Text = sortLabel;

        if (!state.BufferReagents.Any())
        {
            var emptyLabel = new Label { Text = Loc.GetString("chem-master-window-buffer-empty-text") };
            var emptyLabelClassic = new Label { Text = Loc.GetString("chem-master-window-buffer-empty-text") };
            BufferInfo.Children.Add(emptyLabel);
            BufferInfoClassic.Children.Add(emptyLabelClassic);
            return;
        }

        // Buffer volume header row
        void AddBufferHeader(BoxContainer target)
        {
            var hbox = new BoxContainer { Orientation = LayoutOrientation.Horizontal };
            hbox.AddChild(new Label { Text = $"{Loc.GetString("chem-master-window-buffer-label")} " });
            hbox.AddChild(new Label
            {
                Text = $"{state.BufferCurrentVolume}u",
                StyleClasses = { StyleClass.LabelWeak }
            });
            target.AddChild(hbox);
        }
        AddBufferHeader(BufferInfo);
        AddBufferHeader(BufferInfoClassic);

        var reagentList = new List<(ReagentId reagentId, string name, Color color, FixedPoint2 quantity)>();
        foreach (var (reagent, quantity) in state.BufferReagents)
        {
            _prototypeManager.TryIndex(reagent.Prototype, out ReagentPrototype? proto);
            var name = proto?.LocalizedName ?? Loc.GetString("chem-master-window-unknown-reagent-text");
            var reagentColor = proto?.SubstanceColor ?? default(Color);
            reagentList.Add((reagent, name, reagentColor, quantity));
        }

        reagentList = state.SortingType switch
        {
            ChemMasterSortingType.Alphabetical => reagentList.OrderBy(x => x.name).ToList(),
            ChemMasterSortingType.Quantity => reagentList.OrderByDescending(x => x.quantity).ToList(),
            ChemMasterSortingType.Latest => Enumerable.Reverse(reagentList).ToList(),
            _ => reagentList
        };

        var rowCount = 0;
        foreach (var reagent in reagentList)
        {
            BufferInfo.Children.Add(BuildReagentRow(reagent.color, rowCount, reagent.name, reagent.reagentId, reagent.quantity, true, true, modernMode: true));
            BufferInfoClassic.Children.Add(BuildReagentRow(reagent.color, rowCount, reagent.name, reagent.reagentId, reagent.quantity, true, true, modernMode: false));
            rowCount++;
        }

        // A bit messy, but it fixes the search resetting on click.
        if (!string.IsNullOrEmpty(SearchBar.Text))
            UpdateReagentPrototypes(SearchBar.Text);
    }

    private void BuildContainerUI(Control control, ContainerInfo? info, bool addReagentButtons, bool modernMode, string emptyLoc = "chem-master-window-no-container-loaded-text", bool truncateName = true)
    {
        control.Children.Clear();

        if (info is null)
        {
            control.Children.Add(new Label { Text = Loc.GetString(emptyLoc) });
            return;
        }

        control.Children.Add(new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            Children =
            {
                new Label { Text = $"{info.DisplayName}: " },
                new Label
                {
                    Text = $"{info.CurrentVolume}/{info.MaxVolume}",
                    StyleClasses = { StyleClass.LabelWeak }
                }
            }
        });

        var rowCount = 0;

        if (info.PillEntities != null)
        {
            foreach (var (id, quantity) in info.PillEntities)
            {
                control.Children.Add(BuildReagentRow(
                    default,
                    rowCount++,
                    id,
                    default,
                    quantity,
                    false,
                    addReagentButtons,
                    modernMode,
                    truncateName: truncateName));
            }
        }

        if (info.PatchEntities != null)
        {
            foreach (var (id, quantity) in info.PatchEntities)
            {
                control.Children.Add(BuildReagentRow(
                    default,
                    rowCount++,
                    id,
                    default,
                    quantity,
                    false,
                    addReagentButtons,
                    modernMode,
                    truncateName: truncateName));
            }
        }

        if (info.Reagents != null)
        {
            foreach (var reagent in info.Reagents)
            {
                _prototypeManager.TryIndex(reagent.Reagent.Prototype, out ReagentPrototype? proto);
                var name = proto?.LocalizedName ?? Loc.GetString("chem-master-window-unknown-reagent-text");
                var reagentColor = proto?.SubstanceColor ?? default(Color);
                control.Children.Add(BuildReagentRow(reagentColor, rowCount++, name, reagent.Reagent, reagent.Quantity, false, addReagentButtons, modernMode, truncateName: truncateName));
            }
        }
    }

    private Control BuildReagentRow(Color reagentColor, int rowCount, string name, ReagentId reagent, FixedPoint2 quantity, bool isBuffer, bool addReagentButtons, bool modernMode, bool truncateName = true)
    {
        var rowColor1 = Color.FromHex("#1B1B1E");
        var rowColor2 = Color.FromHex("#202025");
        var currentRowColor = (rowCount % 2 == 1) ? rowColor1 : rowColor2;
        var hasColor = reagentColor != default(Color) && addReagentButtons;

        if (modernMode && addReagentButtons)
        {
            // Truncate very long names to prevent UI issues.
            string? toolTip = null;
            if (truncateName)
                (name, toolTip) = TruncateReagentName(name, MaxReagentNameLength);

            // Modern: the entire row is a ReagentButton. Amount is read from the selected amount at click time. If custom amount is selected, send via custom message; otherwise use _selectedAmount.
            var rowBtn = new ReagentButton(string.Empty, _selectedAmount, reagent, isBuffer, StyleClass.ButtonSquare)
            {
                HorizontalExpand = true,
                ToolTip = toolTip, // Labels ignore the mouse, so the tooltip lives on the row button.
            };
            rowBtn.OnPressed += a => { if (_customSelected && _customAmount is {} c) OnCustomReagentButtonPressed?.Invoke(a, reagent, c, isBuffer); else { rowBtn.Amount = _selectedAmount; OnReagentButtonPressed?.Invoke(a, rowBtn); } };

            // Color row at the start of the button
            var row = new PanelContainer
            {
                MinSize = new Vector2(4, 30),
                Margin = new Thickness(-4, 0, 6, 0),
                VerticalAlignment = VAlignment.Center,
                PanelOverride = new StyleBoxFlat
                {
                    BackgroundColor = hasColor ? reagentColor : Color.Transparent,
                }
            };

            var inner = new BoxContainer
            {
                Orientation = LayoutOrientation.Horizontal,
                Children =
                {
                    row,
                    new Label { Text = $"{name}: " },
                    new Label
                    {
                        Text = $"{quantity}u",
                        StyleClasses = { StyleClass.LabelWeak }
                    },
                    new Control { HorizontalExpand = true },
                }
            };
            rowBtn.AddChild(inner);
            return rowBtn;
        }

        // Classic: striped PanelContainer with full per-row amount buttons
        if (reagentColor == default || !addReagentButtons)
            reagentColor = currentRowColor;

        // Truncate very long names to prevent UI issues.
        var classicName = name;
        string? classicToolTip = null;
        if (truncateName)
            (classicName, classicToolTip) = TruncateReagentName(name, MaxClassicReagentNameLength);

        var reagentButtonConstructors = CreateReagentTransferButtons(reagent, isBuffer, addReagentButtons);

        var rowContainer = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            Children =
            {
                new PanelContainer
                {
                    Name = "colorPanel",
                    VerticalExpand = true,
                    MinWidth = 4,
                    PanelOverride = new StyleBoxFlat { BackgroundColor = reagentColor },
                    Margin = new Thickness(0, 1, 4, 1)
                },
                new Label { Text = $"{classicName}: ", ToolTip = classicToolTip, MouseFilter = classicToolTip == null ? MouseFilterMode.Ignore : MouseFilterMode.Stop },
                new Label
                {
                    Text = $"{quantity}u",
                    StyleClasses = { StyleClass.LabelWeak }
                },
                new Control { HorizontalExpand = true },
            }
        };

        foreach (var btn in reagentButtonConstructors)
        {
            rowContainer.AddChild(btn);
        }

        return new PanelContainer
        {
            PanelOverride = new StyleBoxFlat(currentRowColor),
            Children = { rowContainer }
        };
    }

    private void UpdateReagentPrototypes(string? filter = null)
    {
        if (_lastState == null)
            return;

        BufferInfo.Children.Clear();
        BufferInfoClassic.Children.Clear();

        if (!_lastState.BufferReagents.Any())
        {
            BufferInfo.Children.Add(new Label { Text = Loc.GetString("chem-master-window-buffer-empty-text") });
            BufferInfoClassic.Children.Add(new Label { Text = Loc.GetString("chem-master-window-buffer-empty-text") });
            return;
        }

        // Re-add header (mirrors UpdatePanelInfo) so search doesn't hide buffer volume
        void AddHeader(BoxContainer target)
        {
            var h = new BoxContainer { Orientation = LayoutOrientation.Horizontal };
            h.AddChild(new Label { Text = $"{Loc.GetString("chem-master-window-buffer-label")} " });
            h.AddChild(new Label { Text = $"{_lastState.BufferCurrentVolume}u", StyleClasses = { StyleClass.LabelWeak } });
            target.AddChild(h);
        }
        AddHeader(BufferInfo);
        AddHeader(BufferInfoClassic);

        var reagentList = new List<(ReagentId reagentId, string name, Color color, FixedPoint2 quantity)>();
        foreach (var (reagent, quantity) in _lastState.BufferReagents)
        {
            _prototypeManager.TryIndex(reagent.Prototype, out ReagentPrototype? proto);
            var name = proto?.LocalizedName ?? Loc.GetString("chem-master-window-unknown-reagent-text");
            var reagentColor = proto?.SubstanceColor ?? default(Color);
            reagentList.Add((reagent, name, reagentColor, quantity));
        }

        if (!string.IsNullOrEmpty(filter))
        {
            var trimmedFilter = filter.Trim();

            reagentList = reagentList
                .Where(r =>
                    r.name.Contains(
                        trimmedFilter,
                        StringComparison.InvariantCultureIgnoreCase)
                    || r.reagentId.Prototype.ToString().Contains(
                        trimmedFilter,
                        StringComparison.InvariantCultureIgnoreCase))
                .ToList();
        }

        reagentList = _lastState.SortingType switch
        {
            ChemMasterSortingType.Alphabetical => reagentList.OrderBy(x => x.name).ToList(),
            ChemMasterSortingType.Quantity => reagentList.OrderByDescending(x => x.quantity).ToList(),
            ChemMasterSortingType.Latest => Enumerable.Reverse(reagentList).ToList(),
            _ => reagentList
        };

        var rowCount = 0;
        foreach (var reagent in reagentList)
        {
            BufferInfo.Children.Add(BuildReagentRow(reagent.color, rowCount, reagent.name, reagent.reagentId, reagent.quantity, true, true, modernMode: true));
            BufferInfoClassic.Children.Add(BuildReagentRow(reagent.color, rowCount, reagent.name, reagent.reagentId, reagent.quantity, true, true, modernMode: false));
            rowCount++;
        }
    }

    public event Action<ChemMasterReagentAmount>? OnAmountSelected;

    public void SetSelectedAmount(ChemMasterReagentAmount amount)
    {
        _selectedAmount = amount;
        if (!_customSelected)
            CustomAmountButton.Pressed = false;
        SyncGrid(AmountGrid);
    }
}

public sealed class ReagentButton : Button
{
    public ChemMasterReagentAmount Amount { get; set; }
    public readonly bool IsBuffer;
    public ReagentId Id { get; }
    public ReagentButton(string text, ChemMasterReagentAmount amount, ReagentId id, bool isBuffer, string styleClass)
    {
        AddStyleClass(styleClass);
        Text = text;
        Amount = amount;
        Id = id;
        IsBuffer = isBuffer;
    }
}
