// Ported from Frontier Station 14 at commit 5be37d18c2 (2024-07-01), MIT licensed.
// Copyright (c) 2017-2024 New Frontiers. Adapted for Serenity.

using Content.Shared._Serenity.BountyContracts;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Serenity.BountyContracts.UI;

[GenerateTypedNameReferences]
public sealed partial class BountyContractUiFragmentList : Control
{
    public event Action? OnCreateButtonPressed;
    public event Action? OnRefreshButtonPressed;
    public event Action<BountyContract>? OnRemoveButtonPressed;

    public BountyContractUiFragmentList()
    {
        RobustXamlLoader.Load(this);
        CreateButton.OnPressed += _ => OnCreateButtonPressed?.Invoke();
        RefreshButton.OnPressed += _ => OnRefreshButtonPressed?.Invoke();
    }

    public void SetContracts(List<BountyContract> contracts, bool canRemove)
    {
        BountiesContainer.RemoveAllChildren();
        NoContractsLabel.Visible = contracts.Count == 0;

        foreach (var contract in contracts)
        {
            var entry = new BountyContractUiFragmentListEntry(contract, canRemove);
            entry.OnRemoveButtonPressed += c => OnRemoveButtonPressed?.Invoke(c);
            BountiesContainer.AddChild(entry);
        }
    }

    public void SetCanCreate(bool canCreate)
    {
        CreateButton.Disabled = !canCreate;
    }
}
