// Ported from Frontier Station 14 at commit 5be37d18c2 (2024-07-01), MIT licensed.
// Copyright (c) 2017-2024 New Frontiers. Adapted for Serenity.

using System.Linq;
using Content.Shared._Serenity.BountyContracts;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Serenity.BountyContracts.UI;

[GenerateTypedNameReferences]
public sealed partial class BountyContractUiFragmentCreate : Control
{
    public event Action<BountyContractRequest>? OnCreatePressed;
    public event Action? OnCancelPressed;

    private List<BountyContractTargetInfo> _targets = new();
    private List<string> _vessels = new();

    public BountyContractUiFragmentCreate()
    {
        RobustXamlLoader.Load(this);

        CategorySelector.OnItemSelected += opt => OnCategorySelected(opt.Id);
        NameSelector.OnItemSelected += opt => OnNameSelected(opt.Id);
        VesselSelector.OnItemSelected += opt => OnVesselSelected(opt.Id);

        CustomNameButton.OnToggled += args => OnCustomNameToggle(args.Pressed);
        CustomVesselButton.OnToggled += args => OnCustomVesselToggle(args.Pressed);
        NameEdit.OnTextChanged += _ => UpdateDisclaimer();
        RewardEdit.OnTextChanged += _ => UpdateDisclaimer();

        DescriptionEdit.Placeholder = new Rope.Leaf(Loc.GetString("bounty-contracts-ui-create-description-placeholder"));
        RewardEdit.Text = SharedBountyContractSystem.DefaultReward.ToString();

        CreateButton.OnPressed += _ => OnCreatePressed?.Invoke(GetBountyContract());
        CancelButton.OnPressed += _ => OnCancelPressed?.Invoke();

        FillCategories();
        UpdateDisclaimer();
    }

    public void SetPossibleTargets(List<BountyContractTargetInfo> targets)
    {
        _targets = targets.OrderBy(target => target.Name).ToList();

        NameSelector.Clear();
        for (var i = 0; i < _targets.Count; i++)
        {
            NameSelector.AddItem(_targets[i].Name, i);
        }

        OnNameSelected(0);
    }

    public void SetVessels(List<string> vessels)
    {
        vessels.Sort();
        vessels.Insert(0, Loc.GetString("bounty-contracts-ui-create-vessel-unknown"));
        _vessels = vessels;

        VesselSelector.Clear();
        for (var i = 0; i < _vessels.Count; i++)
        {
            VesselSelector.AddItem(_vessels[i], i);
        }

        OnVesselSelected(0);
    }

    private void FillCategories()
    {
        foreach (var (id, meta) in SharedBountyContractSystem.CategoriesMeta)
        {
            CategorySelector.AddItem(Loc.GetString(meta.Name), (byte) id);
        }
    }

    private void UpdateDna(string? dna)
    {
        DnaBox.Visible = !string.IsNullOrEmpty(dna);
        DnaLabel.Text = dna ?? string.Empty;
    }

    private void OnNameSelected(int itemIndex)
    {
        if (itemIndex >= _targets.Count)
        {
            UpdateDna(null);
            UpdateDisclaimer();
            return;
        }

        NameSelector.SelectId(itemIndex);
        UpdateDna(_targets[itemIndex].DNA);
        UpdateDisclaimer();
    }

    private void OnVesselSelected(int itemIndex)
    {
        if (itemIndex >= _vessels.Count)
            return;

        VesselSelector.SelectId(itemIndex);
    }

    private void OnCategorySelected(int id)
    {
        var category = (BountyContractCategory) id;
        CustomNameButton.Pressed = category != BountyContractCategory.Criminal;
        OnCustomNameToggle(CustomNameButton.Pressed);
        CategorySelector.SelectId(id);
    }

    private void OnCustomNameToggle(bool isPressed)
    {
        NameSelector.Visible = !isPressed;
        NameEdit.Visible = isPressed;
        UpdateDna(GetTargetDna());
        UpdateDisclaimer();
    }

    private void OnCustomVesselToggle(bool isPressed)
    {
        VesselSelector.Visible = !isPressed;
        VesselEdit.Visible = isPressed;
        OnVesselSelected(0);
    }

    private void UpdateDisclaimer()
    {
        var reward = GetReward();
        if (reward is null or < 0)
        {
            DisclaimerLabel.SetMessage(Loc.GetString("bounty-contracts-ui-create-error-invalid-price"));
            CreateButton.Disabled = true;
            return;
        }

        if (GetTargetName().Trim().Length == 0)
        {
            DisclaimerLabel.SetMessage(Loc.GetString("bounty-contracts-ui-create-error-no-name"));
            CreateButton.Disabled = true;
            return;
        }

        DisclaimerLabel.SetMessage(Loc.GetString("bounty-contracts-ui-create-ready"));
        CreateButton.Disabled = false;
    }

    private int? GetReward()
    {
        return int.TryParse(RewardEdit.Text, out var price) ? price : null;
    }

    private BountyContractTargetInfo? GetTargetInfo()
    {
        if (CustomNameButton.Pressed)
            return new BountyContractTargetInfo { Name = NameEdit.Text, DNA = null };

        var id = NameSelector.SelectedId;
        return id < _targets.Count ? _targets[id] : null;
    }

    private string GetTargetName()
    {
        return GetTargetInfo()?.Name ?? string.Empty;
    }

    private string? GetTargetDna()
    {
        return GetTargetInfo()?.DNA;
    }

    private string GetVessel()
    {
        if (CustomVesselButton.Pressed)
            return VesselEdit.Text;

        var id = VesselSelector.SelectedId;
        return id < _vessels.Count ? _vessels[id] : string.Empty;
    }

    private BountyContractRequest GetBountyContract()
    {
        return new BountyContractRequest
        {
            Category = (BountyContractCategory) CategorySelector.SelectedId,
            Name = GetTargetName(),
            DNA = GetTargetDna(),
            Vessel = GetVessel(),
            Description = Rope.Collapse(DescriptionEdit.TextRope),
            Reward = GetReward() ?? 0,
        };
    }
}
