using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Serenity.BountyContracts.UI;

[GenerateTypedNameReferences]
public sealed partial class BountyContractUiFragment : BoxContainer
{
    public BountyContractUiFragment()
    {
        RobustXamlLoader.Load(this);
    }
}
