// Ported from Frontier Station 14 at commit 5be37d18c2 (2024-07-01), MIT licensed.
// Copyright (c) 2017-2024 New Frontiers. Adapted for Serenity.

using Content.Shared._Serenity.BountyContracts;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Serenity.BountyContracts.UI;

[GenerateTypedNameReferences]
public sealed partial class BountyContractUiFragmentListEntry : Control
{
    public event Action<BountyContract>? OnRemoveButtonPressed;

    public BountyContractUiFragmentListEntry(BountyContract contract, bool canRemove)
    {
        RobustXamlLoader.Load(this);

        BountyName.Text = contract.Name;

        var vessel = string.IsNullOrEmpty(contract.Vessel)
            ? Loc.GetString("bounty-contracts-ui-create-vessel-unknown")
            : contract.Vessel;
        BountyVessel.Text = Loc.GetString("bounty-contracts-ui-list-vessel", ("vessel", vessel));

        var description = string.IsNullOrEmpty(contract.Description)
            ? Loc.GetString("bounty-contracts-ui-list-no-description")
            : contract.Description;
        BountyDescription.SetMessage(description);

        BountyAuthor.Visible = !string.IsNullOrEmpty(contract.Author);
        if (!string.IsNullOrEmpty(contract.Author))
            BountyAuthor.Text = Loc.GetString("bounty-contracts-ui-list-author", ("author", contract.Author));

        BountyReward.Text = Loc.GetString("cargo-console-menu-points-amount", ("amount", contract.Reward.ToString()));

        RemoveButton.OnPressed += _ => OnRemoveButtonPressed?.Invoke(contract);
        RemoveButton.Disabled = !canRemove;

        var meta = SharedBountyContractSystem.CategoriesMeta[contract.Category];
        BountyPanel.ModulateSelfOverride = meta.UiColor;
        BountyCategory.Text = Loc.GetString("bounty-contracts-ui-list-category", ("category", Loc.GetString(meta.Name)));
    }
}
