# Group
- type: faxGroup
  id: FaxGroupSecurity
  name: fax-group-security
  order: 4000
  color: "#ff4242"

# Base
- type: entity
  abstract: true
  parent: FaxMachineBase
  id: FaxMachineSecurityBase
  components:
    - type: Sprite
      layers:
        - state: icon
          map: [ "base" ]
          color: "#ff4242"

# Fax machines
- type: entity
  parent: FaxMachineSecurityBase
  id: FaxMachineSecurity
  suffix: "MP: Marine Police"
  components:
    - type: Sprite
      layers:
        - state: icon
          map: [ "base" ]
          color: "#ff4242"
    - type: FaxMachine
      group: FaxGroupSecurity
      name: "Marine Police"
      order: 100

- type: entity
  parent: FaxMachineSecurityBase
  id: FaxMachineSecurityHoS
  suffix: "MP: Marine CO"
  components:
    - type: FaxMachine
      group: FaxGroupSecurity
      name: "Marine CO"
      order: 200

- type: entity
  parent: FaxMachineSecurityBase
  id: FaxMachineSecurityWarden
  suffix: "MP: Marine Quartermaster"
  components:
    - type: FaxMachine
      group: FaxGroupSecurity
      name: "Marine Quartermaster"
      order: 300

- type: entity
  parent: FaxMachineSecurityBase
  id: FaxMachineSecurityDetective
  suffix: "MP: Detective"
  components:
    - type: FaxMachine
      group: FaxGroupSecurity
      name: "Detective"
      order: 400

- type: entity
  parent: FaxMachineSecurityBase
  id: FaxMachineSecurityFront
  suffix: "MP: Marine Corpsman"
  components:
    - type: FaxMachine
      group: FaxGroupSecurity
      name: "Marine Corpsman"
      order: 500

- type: entity
  parent: FaxMachineSecurityBase
  id: FaxMachineSecurityPrison
  suffix: "MP: Prison"
  components:
    - type: FaxMachine
      group: FaxGroupSecurity
      name: "Prison"
      order: 600
