using System.Linq;
using Content.Shared._Serenity.Kinks;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Serenity.Kinks.UI;

/// <summary>
/// Read-only view of another player's published kink list, grouped by preference level, for the
/// character inspect window. Reads <see cref="PublishedKinksComponent"/> off the target; the
/// component is absent unless the player has opted in, so absence is the "not published" state.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class CharacterKinksInfoControl : Control
{
    [Dependency] private IPrototypeManager _prototypes = default!;

    // Same order and colours as the editable window, so the two read consistently.
    private static readonly (KinkPreferenceLevel Level, string LocKey, Color Color)[] Groups =
    {
        (KinkPreferenceLevel.Favorite, "kink-preference-favorite", KinkListWindow.ColorFavorite),
        (KinkPreferenceLevel.Yes, "kink-preference-yes", KinkListWindow.ColorYes),
        (KinkPreferenceLevel.Maybe, "kink-preference-maybe", KinkListWindow.ColorMaybe),
        (KinkPreferenceLevel.No, "kink-preference-no", KinkListWindow.ColorNo),
    };

    public CharacterKinksInfoControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void SetCharacter(EntityUid? target, IEntityManager entityManager)
    {
        Levels.RemoveAllChildren();

        if (target == null || !entityManager.TryGetComponent(target.Value, out PublishedKinksComponent? published))
        {
            UnpublishedLabel.Visible = true;
            return;
        }

        UnpublishedLabel.Visible = false;

        foreach (var (level, locKey, color) in Groups)
        {
            var names = published.Kinks
                .Where(kv => kv.Value == level && _prototypes.TryIndex<KinkPrototype>(kv.Key, out _))
                .Select(kv => _prototypes.Index<KinkPrototype>(kv.Key).Name)
                .OrderBy(n => n, StringComparer.OrdinalIgnoreCase)
                .ToList();

            if (names.Count == 0)
                continue;

            var group = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical };
            group.AddChild(new Label
            {
                Text = $"{Loc.GetString(locKey)} ({names.Count})",
                FontColorOverride = color,
                StyleClasses = { "LabelHeading" },
            });
            group.AddChild(new RichTextLabel
            {
                Text = string.Join(", ", names),
                Margin = new Thickness(6, 2, 0, 0),
            });
            Levels.AddChild(group);
        }

        // Opted in but has not rated anything yet.
        if (Levels.ChildCount == 0)
            Levels.AddChild(new Label { Text = Loc.GetString("kinks-info-empty"), Margin = new Thickness(10) });
    }

    public void ClearCharacter()
    {
        Levels.RemoveAllChildren();
        UnpublishedLabel.Visible = true;
    }
}
